// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6PEapvooS-zLh_Vqb6zvqqRI7tQj2TYQ',
    appId: '1:1061912393984:web:2acd3a62b24c0a03eb5be5',
    messagingSenderId: '1061912393984',
    projectId: 'order-tracking-notificat-cf2c7',
    authDomain: 'order-tracking-notificat-cf2c7.firebaseapp.com',
    storageBucket: 'order-tracking-notificat-cf2c7.firebasestorage.app',
    measurementId: 'G-X8GHYML56T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnNzjrOya_GJzgtTV0847YkdcJMoUOcMU',
    appId: '1:1061912393984:android:c5dbe1963b668c30eb5be5',
    messagingSenderId: '1061912393984',
    projectId: 'order-tracking-notificat-cf2c7',
    storageBucket: 'order-tracking-notificat-cf2c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB85RJ5IFhMRl_Caabt476cxxHSj8qZT2s',
    appId: '1:1061912393984:ios:e929458592dc0906eb5be5',
    messagingSenderId: '1061912393984',
    projectId: 'order-tracking-notificat-cf2c7',
    storageBucket: 'order-tracking-notificat-cf2c7.firebasestorage.app',
    iosBundleId: 'com.example.orderTrackingNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB85RJ5IFhMRl_Caabt476cxxHSj8qZT2s',
    appId: '1:1061912393984:ios:e929458592dc0906eb5be5',
    messagingSenderId: '1061912393984',
    projectId: 'order-tracking-notificat-cf2c7',
    storageBucket: 'order-tracking-notificat-cf2c7.firebasestorage.app',
    iosBundleId: 'com.example.orderTrackingNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6PEapvooS-zLh_Vqb6zvqqRI7tQj2TYQ',
    appId: '1:1061912393984:web:230e972b0e0f4609eb5be5',
    messagingSenderId: '1061912393984',
    projectId: 'order-tracking-notificat-cf2c7',
    authDomain: 'order-tracking-notificat-cf2c7.firebaseapp.com',
    storageBucket: 'order-tracking-notificat-cf2c7.firebasestorage.app',
    measurementId: 'G-QEFEWKSVF3',
  );
}
